CREATE TYPE "public"."rezsi_billing_mode" AS ENUM('advance', 'arrears');--> statement-breakpoint
CREATE TYPE "public"."rezsi_checklist_type" AS ENUM('move_in', 'move_out');--> statement-breakpoint
CREATE TYPE "public"."rezsi_document_category" AS ENUM('atadas_atvetel', 'szerzodes', 'marketing', 'egyeb');--> statement-breakpoint
CREATE TYPE "public"."rezsi_invoice_buyer_type" AS ENUM('individual', 'company');--> statement-breakpoint
CREATE TYPE "public"."rezsi_invoice_status" AS ENUM('draft', 'sent', 'paid', 'overdue');--> statement-breakpoint
CREATE TYPE "public"."rezsi_landlord_profile_type" AS ENUM('individual', 'company', 'co_ownership');--> statement-breakpoint
CREATE TYPE "public"."rezsi_ocr_provider" AS ENUM('claude', 'openai', 'gemini', 'tesseract');--> statement-breakpoint
CREATE TYPE "public"."rezsi_payment_method" AS ENUM('stripe', 'cash', 'transfer');--> statement-breakpoint
CREATE TYPE "public"."rezsi_property_type" AS ENUM('lakas', 'uzlet', 'telek', 'egyeb');--> statement-breakpoint
CREATE TYPE "public"."rezsi_reading_source" AS ENUM('manual', 'tenant', 'smart_ttn', 'smart_mqtt', 'home_assistant');--> statement-breakpoint
CREATE TYPE "public"."rezsi_smart_meter_source" AS ENUM('ttn', 'mqtt', 'home_assistant', 'shelly_cloud', 'homewizard');--> statement-breakpoint
CREATE TYPE "public"."rezsi_subscription_status" AS ENUM('active', 'canceled', 'incomplete', 'past_due', 'trialing', 'unpaid', 'paused');--> statement-breakpoint
CREATE TYPE "public"."rezsi_tax_mode" AS ENUM('maganszemely_10pct', 'maganszemely_teteles', 'egyeni_vallalkozo_atalany', 'egyeni_vallalkozo_vszja');--> statement-breakpoint
CREATE TYPE "public"."rezsi_tenant_invitation_status" AS ENUM('pending', 'accepted', 'revoked', 'expired');--> statement-breakpoint
CREATE TYPE "public"."rezsi_todo_priority" AS ENUM('low', 'medium', 'high');--> statement-breakpoint
CREATE TYPE "public"."rezsi_todo_status" AS ENUM('pending', 'in_progress', 'done');--> statement-breakpoint
CREATE TYPE "public"."rezsi_user_role" AS ENUM('landlord', 'tenant', 'admin');--> statement-breakpoint
CREATE TYPE "public"."rezsi_utility_type" AS ENUM('villany', 'viz', 'gaz', 'csatorna', 'internet', 'kozos_koltseg', 'egyeb');--> statement-breakpoint
CREATE TABLE "rezsi_app_setting" (
	"key" varchar(100) PRIMARY KEY NOT NULL,
	"value" text
);
--> statement-breakpoint
CREATE TABLE "rezsi_chat_message" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "rezsi_chat_message_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"propertyId" integer NOT NULL,
	"senderId" integer NOT NULL,
	"senderType" varchar(10) NOT NULL,
	"message" text NOT NULL,
	"attachmentUrl" text,
	"attachmentType" varchar(20),
	"attachmentName" varchar(255),
	"isRead" boolean DEFAULT false NOT NULL,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "rezsi_common_fee_payment" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "rezsi_common_fee_payment_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"commonFeeId" integer NOT NULL,
	"periodDate" date NOT NULL,
	"paid" boolean DEFAULT false NOT NULL,
	"paidDate" date,
	"amount" double precision,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "rezsi_common_fee" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "rezsi_common_fee_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"propertyId" integer NOT NULL,
	"bankAccount" varchar(50),
	"recipient" varchar(200),
	"monthlyAmount" double precision NOT NULL,
	"paymentMemo" varchar(200),
	"frequency" varchar(20) DEFAULT 'monthly' NOT NULL,
	"paymentDay" integer,
	"documentId" integer,
	"includeInRoi" boolean DEFAULT true NOT NULL,
	"isActive" boolean DEFAULT true NOT NULL,
	"validFrom" date,
	"validTo" date,
	"notes" text,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "rezsi_document" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "rezsi_document_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"propertyId" integer NOT NULL,
	"filename" varchar(255) NOT NULL,
	"storedUrl" text NOT NULL,
	"category" "rezsi_document_category" DEFAULT 'egyeb' NOT NULL,
	"notes" text,
	"fileSize" integer,
	"mimeType" varchar(100),
	"uploadedAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "rezsi_handover_checklist" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "rezsi_handover_checklist_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"propertyId" integer NOT NULL,
	"tenantId" integer,
	"checklistType" "rezsi_checklist_type" NOT NULL,
	"step" varchar(50) NOT NULL,
	"status" varchar(20) DEFAULT 'pending' NOT NULL,
	"dataJson" json,
	"completedAt" timestamp with time zone,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "rezsi_invoice_item" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "rezsi_invoice_item_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"invoiceId" integer NOT NULL,
	"description" varchar(255) NOT NULL,
	"quantity" double precision DEFAULT 1 NOT NULL,
	"unit" varchar(20) DEFAULT 'db' NOT NULL,
	"unitPriceHuf" double precision NOT NULL,
	"netAmountHuf" double precision DEFAULT 0 NOT NULL,
	"vatRate" double precision DEFAULT 0 NOT NULL,
	"vatCode" varchar(20) DEFAULT 'TAM' NOT NULL,
	"vatAmountHuf" double precision DEFAULT 0 NOT NULL,
	"grossAmountHuf" double precision DEFAULT 0 NOT NULL,
	"utilityType" "rezsi_utility_type",
	"sourceType" varchar(50),
	"sourceId" integer,
	"sortOrder" integer DEFAULT 0 NOT NULL,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "rezsi_invoice" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "rezsi_invoice_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"landlordId" integer NOT NULL,
	"propertyId" integer NOT NULL,
	"sellerProfileId" integer,
	"tenantId" integer,
	"status" "rezsi_invoice_status" DEFAULT 'draft' NOT NULL,
	"issueDate" date NOT NULL,
	"dueDate" date,
	"fulfillmentDate" date,
	"periodFrom" date,
	"periodTo" date,
	"currency" varchar(3) DEFAULT 'HUF' NOT NULL,
	"paymentMethod" "rezsi_payment_method" DEFAULT 'transfer' NOT NULL,
	"invoiceNumber" varchar(100),
	"provider" varchar(50) DEFAULT 'szamlazz_hu' NOT NULL,
	"providerInvoiceId" varchar(255),
	"pdfUrl" text,
	"sellerDisplayName" varchar(255),
	"sellerName" varchar(255),
	"sellerEmail" varchar(255),
	"sellerAddress" text,
	"sellerTaxNumber" varchar(50),
	"sellerProfileType" "rezsi_landlord_profile_type" DEFAULT 'individual',
	"buyerName" varchar(255) NOT NULL,
	"buyerEmail" varchar(255),
	"buyerAddress" text,
	"buyerTaxNumber" varchar(50),
	"buyerType" "rezsi_invoice_buyer_type" DEFAULT 'individual' NOT NULL,
	"vatCode" varchar(20) DEFAULT 'TAM' NOT NULL,
	"note" text,
	"netTotalHuf" double precision DEFAULT 0 NOT NULL,
	"vatTotalHuf" double precision DEFAULT 0 NOT NULL,
	"grossTotalHuf" double precision DEFAULT 0 NOT NULL,
	"emailedToBuyer" boolean DEFAULT false NOT NULL,
	"reminderSentAt" timestamp with time zone,
	"paidAt" timestamp with time zone,
	"paidAmount" double precision,
	"paidMethod" varchar(50),
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "rezsi_landlord_profile" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "rezsi_landlord_profile_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"ownerUserId" integer NOT NULL,
	"displayName" varchar(255) NOT NULL,
	"profileType" "rezsi_landlord_profile_type" DEFAULT 'individual' NOT NULL,
	"billingName" varchar(255) NOT NULL,
	"billingEmail" varchar(255),
	"billingAddress" text,
	"taxNumber" varchar(50),
	"color" varchar(20),
	"agentKey" text,
	"eInvoice" boolean DEFAULT true NOT NULL,
	"defaultDueDays" integer DEFAULT 5 NOT NULL,
	"defaultVatCode" varchar(20) DEFAULT 'TAM' NOT NULL,
	"isDefault" boolean DEFAULT false NOT NULL,
	"isActive" boolean DEFAULT true NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "rezsi_maintenance_log" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "rezsi_maintenance_log_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"propertyId" integer,
	"description" text NOT NULL,
	"category" varchar(50),
	"costHuf" double precision DEFAULT 0,
	"priority" varchar(20) DEFAULT 'normal' NOT NULL,
	"status" varchar(20) DEFAULT 'pending' NOT NULL,
	"performedBy" varchar(100),
	"performedDate" date,
	"photoUrls" json DEFAULT '[]'::json,
	"documentUrls" json DEFAULT '[]'::json,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "rezsi_marketing_content" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "rezsi_marketing_content_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"propertyId" integer NOT NULL,
	"listingTitle" varchar(200),
	"listingDescription" text,
	"listingUrl" varchar(500),
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "rezsi_meter_info" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "rezsi_meter_info_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"propertyId" integer NOT NULL,
	"utilityType" "rezsi_utility_type" NOT NULL,
	"serialNumber" varchar(100),
	"location" varchar(200),
	"notes" text,
	"photoUrls" jsonb,
	"tariffGroupId" integer,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "rezsi_meter_reading" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "rezsi_meter_reading_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"propertyId" integer NOT NULL,
	"utilityType" "rezsi_utility_type" NOT NULL,
	"meterInfoId" integer,
	"value" double precision NOT NULL,
	"prevValue" double precision,
	"consumption" double precision,
	"tariffId" integer,
	"costHuf" double precision,
	"photoUrl" text,
	"photoUrls" jsonb,
	"readingDate" date NOT NULL,
	"notes" text,
	"source" "rezsi_reading_source" DEFAULT 'manual' NOT NULL,
	"recordedBy" integer,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "rezsi_payment" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "rezsi_payment_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"propertyId" integer NOT NULL,
	"amountHuf" double precision NOT NULL,
	"paymentDate" date NOT NULL,
	"paymentMethod" varchar(50),
	"category" varchar(30),
	"periodFrom" date,
	"periodTo" date,
	"notes" text,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "rezsi_property" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "rezsi_property_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"landlordId" integer NOT NULL,
	"buildingPropertyId" integer,
	"tariffGroupId" integer,
	"collectorId" integer,
	"landlordProfileId" integer,
	"name" varchar(100) NOT NULL,
	"propertyType" varchar(50) DEFAULT 'lakas' NOT NULL,
	"address" text,
	"notes" text,
	"contactName" varchar(100),
	"contactPhone" varchar(30),
	"contactEmail" varchar(120),
	"billingName" varchar(255),
	"billingEmail" varchar(255),
	"billingAddress" text,
	"billingTaxNumber" varchar(50),
	"billingBuyerType" "rezsi_invoice_buyer_type" DEFAULT 'individual' NOT NULL,
	"billingVatCode" varchar(20) DEFAULT 'TAM' NOT NULL,
	"billingMode" "rezsi_billing_mode" DEFAULT 'advance' NOT NULL,
	"billingDueDay" integer DEFAULT 5 NOT NULL,
	"autoBilling" boolean DEFAULT false NOT NULL,
	"autoBillingDay" integer DEFAULT 1 NOT NULL,
	"autoBillingMissingReadings" varchar(20) DEFAULT 'skip_readings' NOT NULL,
	"buildingArea" double precision,
	"landArea" double precision,
	"purchasePrice" double precision,
	"monthlyRent" double precision,
	"rentCurrency" varchar(3) DEFAULT 'HUF' NOT NULL,
	"avatarUrl" text,
	"archived" boolean DEFAULT false NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "rezsi_property_tax" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "rezsi_property_tax_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"propertyId" integer NOT NULL,
	"year" integer NOT NULL,
	"bankAccount" varchar(50),
	"recipient" varchar(200),
	"annualAmount" double precision NOT NULL,
	"installmentAmount" double precision,
	"paymentMemo" varchar(200),
	"deadlineAutumn" date,
	"deadlineSpring" date,
	"autumnPaid" boolean DEFAULT false NOT NULL,
	"autumnPaidDate" date,
	"springPaid" boolean DEFAULT false NOT NULL,
	"springPaidDate" date,
	"documentId" integer,
	"includeInRoi" boolean DEFAULT true NOT NULL,
	"notes" text,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "rezsi_rental_tax_config" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "rezsi_rental_tax_config_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"propertyId" integer NOT NULL,
	"taxMode" "rezsi_tax_mode" DEFAULT 'maganszemely_10pct' NOT NULL,
	"isVatRegistered" boolean DEFAULT false NOT NULL,
	"vatRate" double precision,
	"notes" text,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "rezsi_smart_meter_device" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "rezsi_smart_meter_device_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"propertyId" integer NOT NULL,
	"utilityType" "rezsi_utility_type" NOT NULL,
	"deviceId" varchar(200) NOT NULL,
	"source" "rezsi_smart_meter_source" DEFAULT 'mqtt' NOT NULL,
	"name" varchar(200),
	"ttnAppId" varchar(200),
	"mqttTopic" varchar(500),
	"shellyDeviceId" varchar(200),
	"shellyChannel" integer DEFAULT 0,
	"shellyAuthKey" text,
	"shellyServer" varchar(100),
	"shellyReversedPhases" varchar(10),
	"valueField" varchar(100) DEFAULT 'meter_value' NOT NULL,
	"multiplier" double precision DEFAULT 1 NOT NULL,
	"offset" double precision DEFAULT 0 NOT NULL,
	"deviceUnit" varchar(20),
	"isActive" boolean DEFAULT true NOT NULL,
	"minIntervalMinutes" integer DEFAULT 60 NOT NULL,
	"lastSeenAt" timestamp with time zone,
	"lastRawValue" double precision,
	"lastError" text,
	"meterInfoId" integer,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "rezsi_smart_meter_log" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "rezsi_smart_meter_log_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"deviceId" varchar(200) NOT NULL,
	"source" "rezsi_smart_meter_source" NOT NULL,
	"rawPayload" text,
	"parsedValue" double precision,
	"finalValue" double precision,
	"status" varchar(20) NOT NULL,
	"errorMessage" text,
	"readingId" integer,
	"receivedAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "rezsi_subscription" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "rezsi_subscription_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" integer NOT NULL,
	"stripeCustomerId" varchar(256) NOT NULL,
	"stripeSubscriptionId" varchar(256) NOT NULL,
	"stripePriceId" varchar(256),
	"status" "rezsi_subscription_status" DEFAULT 'incomplete' NOT NULL,
	"currentPeriodStart" timestamp with time zone,
	"currentPeriodEnd" timestamp with time zone,
	"cancelAtPeriodEnd" boolean DEFAULT false NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "rezsi_tariff_group" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "rezsi_tariff_group_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"landlordId" integer NOT NULL,
	"name" varchar(100) NOT NULL,
	"description" text,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "rezsi_tariff" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "rezsi_tariff_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"tariffGroupId" integer NOT NULL,
	"utilityType" "rezsi_utility_type" NOT NULL,
	"rateHuf" double precision NOT NULL,
	"unit" varchar(10) NOT NULL,
	"validFrom" date NOT NULL,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "rezsi_tenancy" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "rezsi_tenancy_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"propertyId" integer NOT NULL,
	"tenantId" integer,
	"tenantName" varchar(200),
	"tenantEmail" varchar(255),
	"tenantPhone" varchar(50),
	"moveInDate" date,
	"moveOutDate" date,
	"leaseMonths" integer,
	"leaseEndDate" date,
	"leaseRenewalNotified" boolean DEFAULT false NOT NULL,
	"depositAmount" double precision,
	"active" boolean DEFAULT true NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "rezsi_tenant_history" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "rezsi_tenant_history_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"propertyId" integer NOT NULL,
	"tenantId" integer,
	"tenantName" varchar(100),
	"tenantEmail" varchar(255),
	"moveInDate" date,
	"moveOutDate" date,
	"depositAmount" double precision,
	"depositReturned" double precision,
	"depositDeductions" double precision,
	"depositNotes" text,
	"totalPayments" double precision,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "rezsi_tenant_invitation" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "rezsi_tenant_invitation_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"landlordId" integer NOT NULL,
	"propertyId" integer NOT NULL,
	"tenantEmail" varchar(255) NOT NULL,
	"tenantName" varchar(255),
	"moveInDate" date,
	"depositAmount" double precision,
	"clerkInvitationId" varchar(255),
	"invitedUserId" integer,
	"status" "rezsi_tenant_invitation_status" DEFAULT 'pending' NOT NULL,
	"invitedAt" timestamp with time zone NOT NULL,
	"acceptedAt" timestamp with time zone,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "rezsi_todo" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "rezsi_todo_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"propertyId" integer,
	"landlordId" integer NOT NULL,
	"title" varchar(200) NOT NULL,
	"description" text,
	"priority" "rezsi_todo_priority" DEFAULT 'medium' NOT NULL,
	"status" "rezsi_todo_status" DEFAULT 'pending' NOT NULL,
	"dueDate" date,
	"completedAt" timestamp with time zone,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "rezsi_user" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "rezsi_user_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"clerkId" varchar(256) NOT NULL,
	"email" varchar(256) NOT NULL,
	"firstName" varchar(256),
	"lastName" varchar(256),
	"phone" varchar(30),
	"imageUrl" text,
	"role" "rezsi_user_role" DEFAULT 'landlord' NOT NULL,
	"locale" varchar(5) DEFAULT 'hu' NOT NULL,
	"theme" varchar(10) DEFAULT 'system' NOT NULL,
	"isActive" boolean DEFAULT true NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "rezsi_wifi_network" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "rezsi_wifi_network_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"propertyId" integer NOT NULL,
	"ssid" varchar(200) NOT NULL,
	"password" varchar(200),
	"securityType" varchar(20) DEFAULT 'WPA2' NOT NULL,
	"location" varchar(200),
	"isPrimary" boolean DEFAULT false NOT NULL,
	"routerIp" varchar(100),
	"routerUser" varchar(100),
	"routerPassword" varchar(200),
	"tailscaleIp" varchar(100),
	"tailscaleDns" varchar(200),
	"notes" text,
	"photoUrls" jsonb,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "rezsi_chat_message" ADD CONSTRAINT "rezsi_chat_message_propertyId_rezsi_property_id_fk" FOREIGN KEY ("propertyId") REFERENCES "public"."rezsi_property"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "rezsi_chat_message" ADD CONSTRAINT "rezsi_chat_message_senderId_rezsi_user_id_fk" FOREIGN KEY ("senderId") REFERENCES "public"."rezsi_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "rezsi_common_fee_payment" ADD CONSTRAINT "rezsi_common_fee_payment_commonFeeId_rezsi_common_fee_id_fk" FOREIGN KEY ("commonFeeId") REFERENCES "public"."rezsi_common_fee"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "rezsi_common_fee" ADD CONSTRAINT "rezsi_common_fee_propertyId_rezsi_property_id_fk" FOREIGN KEY ("propertyId") REFERENCES "public"."rezsi_property"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "rezsi_common_fee" ADD CONSTRAINT "rezsi_common_fee_documentId_rezsi_document_id_fk" FOREIGN KEY ("documentId") REFERENCES "public"."rezsi_document"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "rezsi_document" ADD CONSTRAINT "rezsi_document_propertyId_rezsi_property_id_fk" FOREIGN KEY ("propertyId") REFERENCES "public"."rezsi_property"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "rezsi_handover_checklist" ADD CONSTRAINT "rezsi_handover_checklist_propertyId_rezsi_property_id_fk" FOREIGN KEY ("propertyId") REFERENCES "public"."rezsi_property"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "rezsi_handover_checklist" ADD CONSTRAINT "rezsi_handover_checklist_tenantId_rezsi_user_id_fk" FOREIGN KEY ("tenantId") REFERENCES "public"."rezsi_user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "rezsi_invoice_item" ADD CONSTRAINT "rezsi_invoice_item_invoiceId_rezsi_invoice_id_fk" FOREIGN KEY ("invoiceId") REFERENCES "public"."rezsi_invoice"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "rezsi_invoice" ADD CONSTRAINT "rezsi_invoice_landlordId_rezsi_user_id_fk" FOREIGN KEY ("landlordId") REFERENCES "public"."rezsi_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "rezsi_invoice" ADD CONSTRAINT "rezsi_invoice_propertyId_rezsi_property_id_fk" FOREIGN KEY ("propertyId") REFERENCES "public"."rezsi_property"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "rezsi_invoice" ADD CONSTRAINT "rezsi_invoice_sellerProfileId_rezsi_landlord_profile_id_fk" FOREIGN KEY ("sellerProfileId") REFERENCES "public"."rezsi_landlord_profile"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "rezsi_invoice" ADD CONSTRAINT "rezsi_invoice_tenantId_rezsi_user_id_fk" FOREIGN KEY ("tenantId") REFERENCES "public"."rezsi_user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "rezsi_landlord_profile" ADD CONSTRAINT "rezsi_landlord_profile_ownerUserId_rezsi_user_id_fk" FOREIGN KEY ("ownerUserId") REFERENCES "public"."rezsi_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "rezsi_maintenance_log" ADD CONSTRAINT "rezsi_maintenance_log_propertyId_rezsi_property_id_fk" FOREIGN KEY ("propertyId") REFERENCES "public"."rezsi_property"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "rezsi_marketing_content" ADD CONSTRAINT "rezsi_marketing_content_propertyId_rezsi_property_id_fk" FOREIGN KEY ("propertyId") REFERENCES "public"."rezsi_property"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "rezsi_meter_info" ADD CONSTRAINT "rezsi_meter_info_propertyId_rezsi_property_id_fk" FOREIGN KEY ("propertyId") REFERENCES "public"."rezsi_property"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "rezsi_meter_info" ADD CONSTRAINT "rezsi_meter_info_tariffGroupId_rezsi_tariff_group_id_fk" FOREIGN KEY ("tariffGroupId") REFERENCES "public"."rezsi_tariff_group"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "rezsi_meter_reading" ADD CONSTRAINT "rezsi_meter_reading_propertyId_rezsi_property_id_fk" FOREIGN KEY ("propertyId") REFERENCES "public"."rezsi_property"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "rezsi_meter_reading" ADD CONSTRAINT "rezsi_meter_reading_meterInfoId_rezsi_meter_info_id_fk" FOREIGN KEY ("meterInfoId") REFERENCES "public"."rezsi_meter_info"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "rezsi_meter_reading" ADD CONSTRAINT "rezsi_meter_reading_tariffId_rezsi_tariff_id_fk" FOREIGN KEY ("tariffId") REFERENCES "public"."rezsi_tariff"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "rezsi_meter_reading" ADD CONSTRAINT "rezsi_meter_reading_recordedBy_rezsi_user_id_fk" FOREIGN KEY ("recordedBy") REFERENCES "public"."rezsi_user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "rezsi_payment" ADD CONSTRAINT "rezsi_payment_propertyId_rezsi_property_id_fk" FOREIGN KEY ("propertyId") REFERENCES "public"."rezsi_property"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "rezsi_property" ADD CONSTRAINT "rezsi_property_landlordId_rezsi_user_id_fk" FOREIGN KEY ("landlordId") REFERENCES "public"."rezsi_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "rezsi_property" ADD CONSTRAINT "rezsi_property_tariffGroupId_rezsi_tariff_group_id_fk" FOREIGN KEY ("tariffGroupId") REFERENCES "public"."rezsi_tariff_group"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "rezsi_property" ADD CONSTRAINT "rezsi_property_collectorId_rezsi_user_id_fk" FOREIGN KEY ("collectorId") REFERENCES "public"."rezsi_user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "rezsi_property" ADD CONSTRAINT "rezsi_property_landlordProfileId_rezsi_landlord_profile_id_fk" FOREIGN KEY ("landlordProfileId") REFERENCES "public"."rezsi_landlord_profile"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "rezsi_property_tax" ADD CONSTRAINT "rezsi_property_tax_propertyId_rezsi_property_id_fk" FOREIGN KEY ("propertyId") REFERENCES "public"."rezsi_property"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "rezsi_property_tax" ADD CONSTRAINT "rezsi_property_tax_documentId_rezsi_document_id_fk" FOREIGN KEY ("documentId") REFERENCES "public"."rezsi_document"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "rezsi_rental_tax_config" ADD CONSTRAINT "rezsi_rental_tax_config_propertyId_rezsi_property_id_fk" FOREIGN KEY ("propertyId") REFERENCES "public"."rezsi_property"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "rezsi_smart_meter_device" ADD CONSTRAINT "rezsi_smart_meter_device_propertyId_rezsi_property_id_fk" FOREIGN KEY ("propertyId") REFERENCES "public"."rezsi_property"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "rezsi_smart_meter_device" ADD CONSTRAINT "rezsi_smart_meter_device_meterInfoId_rezsi_meter_info_id_fk" FOREIGN KEY ("meterInfoId") REFERENCES "public"."rezsi_meter_info"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "rezsi_smart_meter_log" ADD CONSTRAINT "rezsi_smart_meter_log_readingId_rezsi_meter_reading_id_fk" FOREIGN KEY ("readingId") REFERENCES "public"."rezsi_meter_reading"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "rezsi_subscription" ADD CONSTRAINT "rezsi_subscription_userId_rezsi_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."rezsi_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "rezsi_tariff_group" ADD CONSTRAINT "rezsi_tariff_group_landlordId_rezsi_user_id_fk" FOREIGN KEY ("landlordId") REFERENCES "public"."rezsi_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "rezsi_tariff" ADD CONSTRAINT "rezsi_tariff_tariffGroupId_rezsi_tariff_group_id_fk" FOREIGN KEY ("tariffGroupId") REFERENCES "public"."rezsi_tariff_group"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "rezsi_tenancy" ADD CONSTRAINT "rezsi_tenancy_propertyId_rezsi_property_id_fk" FOREIGN KEY ("propertyId") REFERENCES "public"."rezsi_property"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "rezsi_tenancy" ADD CONSTRAINT "rezsi_tenancy_tenantId_rezsi_user_id_fk" FOREIGN KEY ("tenantId") REFERENCES "public"."rezsi_user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "rezsi_tenant_history" ADD CONSTRAINT "rezsi_tenant_history_propertyId_rezsi_property_id_fk" FOREIGN KEY ("propertyId") REFERENCES "public"."rezsi_property"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "rezsi_tenant_history" ADD CONSTRAINT "rezsi_tenant_history_tenantId_rezsi_user_id_fk" FOREIGN KEY ("tenantId") REFERENCES "public"."rezsi_user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "rezsi_tenant_invitation" ADD CONSTRAINT "rezsi_tenant_invitation_landlordId_rezsi_user_id_fk" FOREIGN KEY ("landlordId") REFERENCES "public"."rezsi_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "rezsi_tenant_invitation" ADD CONSTRAINT "rezsi_tenant_invitation_propertyId_rezsi_property_id_fk" FOREIGN KEY ("propertyId") REFERENCES "public"."rezsi_property"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "rezsi_tenant_invitation" ADD CONSTRAINT "rezsi_tenant_invitation_invitedUserId_rezsi_user_id_fk" FOREIGN KEY ("invitedUserId") REFERENCES "public"."rezsi_user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "rezsi_todo" ADD CONSTRAINT "rezsi_todo_propertyId_rezsi_property_id_fk" FOREIGN KEY ("propertyId") REFERENCES "public"."rezsi_property"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "rezsi_todo" ADD CONSTRAINT "rezsi_todo_landlordId_rezsi_user_id_fk" FOREIGN KEY ("landlordId") REFERENCES "public"."rezsi_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "rezsi_wifi_network" ADD CONSTRAINT "rezsi_wifi_network_propertyId_rezsi_property_id_fk" FOREIGN KEY ("propertyId") REFERENCES "public"."rezsi_property"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "chat_message_property_id_idx" ON "rezsi_chat_message" USING btree ("propertyId");--> statement-breakpoint
CREATE INDEX "chat_message_sender_id_idx" ON "rezsi_chat_message" USING btree ("senderId");--> statement-breakpoint
CREATE INDEX "common_fee_payment_fee_id_idx" ON "rezsi_common_fee_payment" USING btree ("commonFeeId");--> statement-breakpoint
CREATE INDEX "common_fee_property_id_idx" ON "rezsi_common_fee" USING btree ("propertyId");--> statement-breakpoint
CREATE INDEX "document_property_id_idx" ON "rezsi_document" USING btree ("propertyId");--> statement-breakpoint
CREATE INDEX "handover_checklist_property_id_idx" ON "rezsi_handover_checklist" USING btree ("propertyId");--> statement-breakpoint
CREATE INDEX "invoice_item_invoice_id_idx" ON "rezsi_invoice_item" USING btree ("invoiceId");--> statement-breakpoint
CREATE INDEX "invoice_landlord_id_idx" ON "rezsi_invoice" USING btree ("landlordId");--> statement-breakpoint
CREATE INDEX "invoice_property_id_idx" ON "rezsi_invoice" USING btree ("propertyId");--> statement-breakpoint
CREATE INDEX "invoice_status_idx" ON "rezsi_invoice" USING btree ("status");--> statement-breakpoint
CREATE UNIQUE INDEX "invoice_provider_invoice_id_idx" ON "rezsi_invoice" USING btree ("providerInvoiceId");--> statement-breakpoint
CREATE INDEX "landlord_profile_owner_user_id_idx" ON "rezsi_landlord_profile" USING btree ("ownerUserId");--> statement-breakpoint
CREATE INDEX "landlord_profile_default_idx" ON "rezsi_landlord_profile" USING btree ("ownerUserId","isDefault");--> statement-breakpoint
CREATE INDEX "maintenance_log_property_id_idx" ON "rezsi_maintenance_log" USING btree ("propertyId");--> statement-breakpoint
CREATE UNIQUE INDEX "marketing_content_property_id_idx" ON "rezsi_marketing_content" USING btree ("propertyId");--> statement-breakpoint
CREATE INDEX "meter_info_property_id_idx" ON "rezsi_meter_info" USING btree ("propertyId");--> statement-breakpoint
CREATE INDEX "meter_reading_property_id_idx" ON "rezsi_meter_reading" USING btree ("propertyId");--> statement-breakpoint
CREATE INDEX "meter_reading_date_idx" ON "rezsi_meter_reading" USING btree ("readingDate");--> statement-breakpoint
CREATE INDEX "meter_reading_utility_idx" ON "rezsi_meter_reading" USING btree ("propertyId","utilityType");--> statement-breakpoint
CREATE INDEX "meter_reading_meter_info_idx" ON "rezsi_meter_reading" USING btree ("meterInfoId","readingDate");--> statement-breakpoint
CREATE INDEX "payment_property_id_idx" ON "rezsi_payment" USING btree ("propertyId");--> statement-breakpoint
CREATE INDEX "payment_date_idx" ON "rezsi_payment" USING btree ("paymentDate");--> statement-breakpoint
CREATE INDEX "property_landlord_id_idx" ON "rezsi_property" USING btree ("landlordId");--> statement-breakpoint
CREATE INDEX "property_building_id_idx" ON "rezsi_property" USING btree ("buildingPropertyId");--> statement-breakpoint
CREATE INDEX "property_tax_property_id_idx" ON "rezsi_property_tax" USING btree ("propertyId");--> statement-breakpoint
CREATE UNIQUE INDEX "rental_tax_config_property_id_idx" ON "rezsi_rental_tax_config" USING btree ("propertyId");--> statement-breakpoint
CREATE UNIQUE INDEX "smart_meter_device_id_idx" ON "rezsi_smart_meter_device" USING btree ("deviceId");--> statement-breakpoint
CREATE INDEX "smart_meter_property_id_idx" ON "rezsi_smart_meter_device" USING btree ("propertyId");--> statement-breakpoint
CREATE INDEX "smart_meter_log_device_id_idx" ON "rezsi_smart_meter_log" USING btree ("deviceId");--> statement-breakpoint
CREATE INDEX "subscription_stripe_customer_id_idx" ON "rezsi_subscription" USING btree ("stripeCustomerId");--> statement-breakpoint
CREATE UNIQUE INDEX "subscription_stripe_subscription_id_idx" ON "rezsi_subscription" USING btree ("stripeSubscriptionId");--> statement-breakpoint
CREATE INDEX "subscription_user_id_idx" ON "rezsi_subscription" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "tariff_group_landlord_id_idx" ON "rezsi_tariff_group" USING btree ("landlordId");--> statement-breakpoint
CREATE INDEX "tariff_group_id_idx" ON "rezsi_tariff" USING btree ("tariffGroupId");--> statement-breakpoint
CREATE INDEX "tenancy_property_id_idx" ON "rezsi_tenancy" USING btree ("propertyId");--> statement-breakpoint
CREATE INDEX "tenancy_tenant_id_idx" ON "rezsi_tenancy" USING btree ("tenantId");--> statement-breakpoint
CREATE INDEX "tenant_history_property_id_idx" ON "rezsi_tenant_history" USING btree ("propertyId");--> statement-breakpoint
CREATE INDEX "tenant_invitation_landlord_id_idx" ON "rezsi_tenant_invitation" USING btree ("landlordId");--> statement-breakpoint
CREATE INDEX "tenant_invitation_property_id_idx" ON "rezsi_tenant_invitation" USING btree ("propertyId");--> statement-breakpoint
CREATE INDEX "tenant_invitation_email_idx" ON "rezsi_tenant_invitation" USING btree ("tenantEmail");--> statement-breakpoint
CREATE INDEX "todo_property_id_idx" ON "rezsi_todo" USING btree ("propertyId");--> statement-breakpoint
CREATE INDEX "todo_landlord_id_idx" ON "rezsi_todo" USING btree ("landlordId");--> statement-breakpoint
CREATE UNIQUE INDEX "user_clerk_id_idx" ON "rezsi_user" USING btree ("clerkId");--> statement-breakpoint
CREATE INDEX "user_email_idx" ON "rezsi_user" USING btree ("email");--> statement-breakpoint
CREATE INDEX "wifi_network_property_id_idx" ON "rezsi_wifi_network" USING btree ("propertyId");